'''
Emotional Consistency Test
===========================
Tests whether the bot's *internal* emotional state (generated by the emotion
generator) is consistent with the emotion *expressed* in its actual text reply
(detected by EmoBART).

Flow for each sample sentence:
  1. Use the SENTENCES dict key as the ground-truth user_emotion (intensity fixed
     at 0.75), identical to the approach used in mirroring_test.py.
  2. generate_bot_emotion        → bot_internal_emotion
  3. generate_bot_response       → bot_response_text   (no memory / single turn)
  4. EmoBART analyses the reply  → bot_expressed_emotion
  5. Compare bot_internal_emotion vs bot_expressed_emotion

Results are saved as:
  tests_results/consistency_results_<PersonalityName>.json
  tests_results/consistency_heatmap_<PersonalityName>.png

The heatmap rows = bot internal emotion, columns = bot expressed emotion.
A perfectly consistent bot produces counts only on the main diagonal.

Test sentences and emotion labels are reused from mirroring_test.py so that
all three evaluations (mirroring, BFI-44, emotional consistency) share the
same stimulus set.
'''

import os
import sys
import json
import time
from collections import defaultdict

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

sys.path.append(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from personality import PersonalityProfile, OCEANTraitDescription
from emotion_generator import generate_bot_emotion
from emotion_recognizer_bart import get_emobart_tokenizer_and_model, get_user_emotional_status
from response_generator import generate_bot_response
from configs import TEST_FOLDER
from mirroring_test import EKMAN_EMOTIONS, SENTENCES

N_SENTENCES_PER_EMOTION = 5
OCEAN_DESC = OCEANTraitDescription()

def load_personalities_from_file() -> dict:
    """Loads personalities.json from the project root (one level up if needed)."""
    candidates = [
        os.path.join(os.path.dirname(os.path.abspath(__file__)), 'personalities.json'),
        os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'personalities.json'),
    ]
    for path in candidates:
        if os.path.exists(path):
            with open(path, 'r') as f:
                return json.load(f)
    return {
        'Bob': {
            'name': 'Bob',
            'background': '15 years old highschool student. Likes pasta with tomato sauce. Dislikes dogs.',
            'openness': 'low', 'conscientiousness': 'high', 'extraversion': 'low',
            'agreeableness': 'low', 'neuroticism': 'high', 'comfortability': True
        }
    }

def choose_personality() -> PersonalityProfile | None:
    """Interactive menu to pick a personality profile."""
    profiles = load_personalities_from_file()
    names = list(profiles.keys())

    print('\n--- Available Personalities ---')
    for i, name in enumerate(names, 1):
        print(f'  {i}. {name}  –  {profiles[name]["background"]}')

    choice = input('\nSelect a personality number (or "c" to cancel): ').strip()
    if choice.isdigit() and 1 <= int(choice) <= len(names):
        p_data = profiles[names[int(choice) - 1]]
        personality = PersonalityProfile(
            p_data['name'], p_data['background'],
            p_data['openness'], p_data['conscientiousness'],
            p_data['extraversion'], p_data['agreeableness'],
            p_data['neuroticism'], p_data.get('comfortability', True),
            OCEAN_DESC
        )
        print(f"\nPersonality selected: {personality.name}")
        return personality

    print('\nCancelled.')
    return None

def run_consistency_test(
    personality: PersonalityProfile,
    sentences: dict[str, list[str]]
) -> dict:
    """
    For every (user_emotion_label, sentence) pair:
      1. Use the dict key as user_emotion (intensity fixed at 0.75) — no EmoBART
      2. Emotion generator → bot_internal_emotion
      3. Response generator → bot_response_text   (no memory)
      4. EmoBART on the reply → bot_expressed_emotion
      5. Record (bot_internal_emotion, bot_expressed_emotion) pair

    Returns a nested dict:
        results[bot_internal_emotion][bot_expressed_emotion] = count
    """
    print('\nLoading EmoBART (used only to evaluate bot replies)...')
    tokenizer, emobart_model = get_emobart_tokenizer_and_model()

    total_calls = len(EKMAN_EMOTIONS) * N_SENTENCES_PER_EMOTION
    call_count = 0

    print(f'\n{"="*64}')
    print(f'  Emotional Consistency Test')
    print(f'  Personality : {personality.name}')
    print(f'  Comfortability : {personality.comfortability}')
    print(f'  Total samples: {total_calls}')
    print(f'{"="*64}\n')

    results: dict[str, dict[str, int]] = {
        e: defaultdict(int) for e in EKMAN_EMOTIONS
    }
    sample_log: list[dict] = []

    for user_emotion_label, sentence_list in sentences.items():
        for sentence in sentence_list:
            call_count += 1
            print(
                f'  [{call_count:03d}/{total_calls}]  '
                f'label={user_emotion_label:<9s}  '
                f'"{sentence[:55]}"...'
            )

            user_emotion = user_emotion_label
            user_intensity = 0.75

            bot_internal_emotion = 'neutral'
            for attempt in range(3):
                try:
                    raw = generate_bot_emotion(
                        user_text=sentence,
                        user_emotion=user_emotion,
                        user_emotion_intensity=user_intensity,
                        bot_personality=personality,
                        bot_thoughts_on_user='',
                        recent_turns=[],
                    )
                    candidate = raw.strip().lower().split()[0] if raw.strip() else 'neutral'
                    if candidate not in EKMAN_EMOTIONS:
                        for known in EKMAN_EMOTIONS:
                            if known in raw.lower():
                                candidate = known
                                break
                        else:
                            candidate = 'neutral'
                    bot_internal_emotion = candidate
                    break
                except Exception as exc:
                    if attempt < 2:
                        print(f'    [emotion gen] retry ({exc})')
                        time.sleep(2)
                    else:
                        print(f'    [emotion gen] FAILED – defaulting to neutral')

            bot_response_text = ''
            for attempt in range(3):
                try:
                    bot_response_text = generate_bot_response(
                        user_text=sentence,
                        user_emotion=user_emotion,
                        user_emotion_intensity=user_intensity,
                        bot_personality=personality,
                        bot_thoughts_on_user='',
                        recent_turns=[],
                        relevant_memories=[],
                        bot_emotion=bot_internal_emotion
                    )
                    break
                except Exception as exc:
                    if attempt < 2:
                        print(f'    [response gen] retry ({exc})')
                        time.sleep(2)
                    else:
                        print(f'    [response gen] FAILED')

            bot_expressed_emotion = 'neutral'
            if bot_response_text.strip():
                try:
                    expressed_raw, _ = get_user_emotional_status(
                        tokenizer, emobart_model, bot_response_text
                    )
                    bot_expressed_emotion = expressed_raw
                except Exception as exc:
                    print(f'    [EmoBART reply] FAILED: {exc}')

            if bot_internal_emotion not in EKMAN_EMOTIONS:
                bot_internal_emotion = 'neutral'
            if bot_expressed_emotion not in EKMAN_EMOTIONS:
                bot_expressed_emotion = 'neutral'

            results[bot_internal_emotion][bot_expressed_emotion] += 1

            is_consistent = '✓ CONSISTENT' if bot_internal_emotion == bot_expressed_emotion else '✗ mismatch  '
            print(
                f'    internal={bot_internal_emotion:<9s}  '
                f'expressed={bot_expressed_emotion:<9s}  {is_consistent}'
            )
            print(f'    reply: "{bot_response_text[:90]}"')

            sample_log.append({
                'user_emotion_label': user_emotion_label,
                'sentence': sentence,
                'bot_internal_emotion': bot_internal_emotion,
                'bot_response': bot_response_text,
                'bot_expressed_emotion': bot_expressed_emotion,
                'consistent': bot_internal_emotion == bot_expressed_emotion,
            })

        print()

    return {'matrix': results, 'samples': sample_log}

def compute_consistency_rate(matrix: dict[str, dict[str, int]]) -> float:
    """Fraction of samples where internal == expressed emotion."""
    total = consistent = 0
    for internal, expressed_counts in matrix.items():
        for expressed, count in expressed_counts.items():
            total += count
            if internal == expressed:
                consistent += count
    return consistent / total if total > 0 else 0.0

def print_summary(p_name: str, matrix: dict[str, dict[str, int]], samples: list[dict]) -> None:
    rate = compute_consistency_rate(matrix)
    total = sum(sum(v.values()) for v in matrix.values())
    consistent = int(rate * total)

    print('\n' + '=' * 64)
    print('  EMOTIONAL CONSISTENCY SUMMARY')
    print(f'  Personality : {p_name}')
    print(f'  Consistent samples : {consistent} / {total}  ({rate*100:.1f}%)')
    print('=' * 64)

    print('\n  Per-internal-emotion breakdown:\n')
    for internal in EKMAN_EMOTIONS:
        counts = matrix.get(internal, {})
        n = sum(counts.values())
        if n == 0:
            continue
        cons = counts.get(internal, 0)
        pct = cons / n * 100
        top = sorted(counts.items(), key=lambda x: -x[1])[:3]
        top_str = ', '.join(f'{e}={c}' for e, c in top)
        bar = '█' * int(pct / 5)
        print(f'  internal={internal:<9s}  consistent={pct:5.1f}%  {bar}')
        print(f'    top expressed: [{top_str}]')
    print()

def save_heatmap(p_name: str, matrix: dict[str, dict[str, int]], output_dir: str) -> str:
    """
    Heatmap:  rows = bot internal emotion,  cols = bot expressed emotion.
    Perfect consistency → counts on the main diagonal only.
    """
    mat = np.zeros((len(EKMAN_EMOTIONS), len(EKMAN_EMOTIONS)), dtype=int)
    for i, internal in enumerate(EKMAN_EMOTIONS):
        for j, expressed in enumerate(EKMAN_EMOTIONS):
            mat[i, j] = matrix.get(internal, {}).get(expressed, 0)

    rate = compute_consistency_rate(matrix)
    total = mat.sum()

    fig, ax = plt.subplots(figsize=(9, 7))
    im = ax.imshow(mat, cmap='Blues', aspect='auto', vmin=0)

    ax.set_xticks(range(len(EKMAN_EMOTIONS)))
    ax.set_yticks(range(len(EKMAN_EMOTIONS)))
    ax.set_xticklabels(EKMAN_EMOTIONS, rotation=45, ha='right', fontsize=11)
    ax.set_yticklabels(EKMAN_EMOTIONS, fontsize=11)
    ax.set_xlabel('Bot expressed emotion (from response text via EmoBART)', fontsize=11)
    ax.set_ylabel('Bot internal emotion (from emotion generator)', fontsize=11)
    ax.set_title(
        f'Emotional Consistency Heatmap\n'
        f'{p_name}  –  consistency rate: {rate*100:.1f}%  ({int(rate*total)}/{total} samples)',
        fontsize=12, pad=14
    )
    vmax = mat.max() if mat.max() > 0 else 1
    for i in range(len(EKMAN_EMOTIONS)):
        for j in range(len(EKMAN_EMOTIONS)):
            val = mat[i, j]
            color = 'white' if val > vmax * 0.6 else 'black'
            ax.text(j, i, f'{val}',
                    ha='center', va='center', fontsize=8, color=color)

    plt.colorbar(im, ax=ax, label='Count', shrink=0.8)
    plt.tight_layout()

    safe_name = p_name.replace(' ', '_').replace('/', '-')
    path = os.path.join(output_dir, f'consistency_heatmap_{safe_name}.png')
    plt.savefig(path, dpi=150)
    plt.close()
    print(f'  Heatmap saved → {path}')
    return path


def save_results_json(
    p_name: str,
    matrix: dict[str, dict[str, int]],
    samples: list[dict],
    output_dir: str,
) -> str:
    """Saves raw results (matrix + per-sample log) to JSON."""
    serialisable_matrix = {
        internal: dict(expressed_counts)
        for internal, expressed_counts in matrix.items()
    }
    payload = {
        'personality': p_name,
        'consistency_rate': compute_consistency_rate(matrix),
        'matrix': serialisable_matrix,
        'samples': samples,
    }
    safe_name = p_name.replace(' ', '_').replace('/', '-')
    path = os.path.join(output_dir, f'consistency_results_{safe_name}.json')
    with open(path, 'w') as f:
        json.dump(payload, f, indent=2)
    print(f'  Results JSON saved → {path}')
    return path

def main():
    output_dir = TEST_FOLDER
    os.makedirs(output_dir, exist_ok=True)

    personality = choose_personality()
    if not personality:
        print('Exiting.')
        return

    data = run_consistency_test(
        personality=personality,
        sentences=SENTENCES
    )

    matrix  = data['matrix']
    samples = data['samples']

    print_summary(personality.name, matrix, samples)

    save_results_json(personality.name, matrix, samples, output_dir)

    print('\n  Generating heatmap...')
    save_heatmap(personality.name, matrix, output_dir)

    print('\nEmotional Consistency Test complete.\n')


if __name__ == '__main__':
    main()